### PR TITLE
Documented basic test procedure

### PR DESCRIPTION
**Pull request by adamwolf**
This is not ready for merge yet, but as we finish the "check" issues, let's add them here.

### CODE REVIEW

**Comment by nickoe** [comment]
Maybe add below sanity checks:
 - Open python console
 - Run a footprint wizard script in the footprint editor
 - Run the 3D viewer
 - Run the python tests in the qa folder

**Comment by adamwolf** [comment]
I think these are all good.  Do you know the steps we'd have to do to test
them?

**Comment by nickoe** [comment]
When you say "them", I guess you are reffering to the tests in the qa folder. You simply run the test.py file in the qa folder as you would run any other script on the commandline in an environment where you expect to be able to import pcbnew.

**Comment by adamwolf** [comment]
I'm going to merge and close this, and add the remaining items to issues.  Thanks nick!

**Pull request merged**
