### PR TITLE
Python framework

### LINKED ISSUE #74: Build failure after "Python built as a Framework."
With the new change "Python built as a Framework." (https://github.com/wayneandlayne/kicad-mac-builder/commit/538c743e37bd002d1795acce51d032ca9ef5bc77) I get this build error:
```
09:54:39 Building './Python Launcher.app'
09:54:39 Copying files
09:54:39 Done.
09:54:39 test -d "/Applications/Python 2.7" || mkdir -p "/Applications/Python 2.7"
09:54:39 mkdir: /Applications/Python 2.7: Permission denied
```
See http://ci.kicad-pcb.org/job/osx-kicad-adam-new-head/94/console

Using `./build.sh package-kicad-unified package-kicad-nightly package-extras` to build.

### PR DESCRIPTION
**Pull request by adamwolf**
Meant to fix #74.

Includes KiCad patch for Python bundles.  This has already been sent to the KiCad dev list.

I don't really like the Python patch, but I tried 2 different ways that were cleaner and neither of them worked. :(

### CODE REVIEW

**Comment by adamwolf** [comment]
@nickoe can you get Jenkins to build this branch tonight?

**Comment by nickoe** [comment]
I triggered this build if you are curious, http://ci.kicad-pcb.org/job/osx-kicad-adam-new-head/96/console

**Comment by adamwolf** [comment]
Thanks!  *Sigh* :). I'll have another patch set tonight...

Adam

**Comment by adamwolf** [comment]
Look at that, it built on my 10.11 Jenkins automatically!  Going to merge this in.

**Pull request merged**
